### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "email": "lihin57345@dizigg.com",
    "password": "TestPassword123"
}

### Email test
POST http://localhost:3000/api/mail
Content-Type: application/json

{
    "subject": "Test Email",
    "text": "This is a test email",
    "to": "hackkill74@gmail.com",
    "from": ""
}

### Validar email
PUT http://localhost:3000/api/user/validatemail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUwZmNmODRjMjNjZWQzNDE2MzYyYiIsImVtYWlsIjoidGVzdHVzZXIxMEBnbWFpbC5jb20iLCJpYXQiOjE3NDMwNjUwNDAsImV4cCI6MTc0MzA2ODY0MH0.23jy2Vbh861Lr6lTERgcL_Gtb4ZCEjuoXhebrEy0GKc
Content-Type: application/json

{
    "code": "556448" 
}

### Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "testuser12@gmail.com",
    "password": "TestPassword123"
}

### Actualizar datos personales
PUT http://localhost:3000/api/user/personadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxY2VmNDE4M2Y4NDUxZTBmMGY4ZCIsImVtYWlsIjoidGVzdHVzZXIxM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMwNjg0MDEsImV4cCI6MTc0MzA3MjAwMX0.HUrM75fS9eSLSB19VT3jMlz6lNO1X_1rVIJ7awk4geA

{
    "name": "Ivan",
    "surname": "Guerrero",
    "nif": "12345678P"
}

### Comprobar guardado datos persona (OBSOLETO)
GET http://localhost:3000/api/user/persona
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxY2VmNDE4M2Y4NDUxZTBmMGY4ZCIsImVtYWlsIjoidGVzdHVzZXIxM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMxMDE4NDYsImV4cCI6MTc0MzEwNTQ0Nn0.Ox-ipmTqzWmE0YZTtzLVKJDnLtafui7haDC0cOovxjc


### Actualizar datos compañía
PATCH http://localhost:3000/api/user/companydata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxY2VmNDE4M2Y4NDUxZTBmMGY4ZCIsImVtYWlsIjoidGVzdHVzZXIxM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMwNjg0MDEsImV4cCI6MTc0MzA3MjAwMX0.HUrM75fS9eSLSB19VT3jMlz6lNO1X_1rVIJ7awk4geA

{
    "companyName": "U-tad",
    "cif": "A12345678",
    "address": "Calle Prueba, 123",
    "number": 123,
    "postal": 28290,
    "city": "Madrid",
    "province": "Madrid"
}

### Subir logo a IPFS
PATCH http://localhost:3000/api/user/logo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxY2VmNDE4M2Y4NDUxZTBmMGY4ZCIsImVtYWlsIjoidGVzdHVzZXIxM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMwOTk3MzUsImV4cCI6MTc0MzEwMzMzNX0.CXr6LPwaGWPZqo1yDA6YjSuuWRLRcnj4jZvDXYh4PtY
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< C:\Users\theiv\Downloads\logo.png
--boundary123--

### GetUser
GET http://localhost:3000/api/user/getuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxY2VmNDE4M2Y4NDUxZTBmMGY4ZCIsImVtYWlsIjoidGVzdHVzZXIxM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMxMDE5MzAsImV4cCI6MTc0MzEwNTUzMH0.5lj3e2ctgCfkjIYvfdJLhQRaZ1sikBQn4wU4q1exlKQ

### DeleteUser (soft)
DELETE http://localhost:3000/api/user/deleteuser?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxY2VmNDE4M2Y4NDUxZTBmMGY4ZCIsImVtYWlsIjoidGVzdHVzZXIxM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMxMDIxMjMsImV4cCI6MTc0MzEwNTcyM30.m87N5gQtFXFYfEYE7EiQnPsIF1ft8yweNnpW5kSsFQM

### DeleteUser (hard)
DELETE http://localhost:3000/api/user/deleteuser?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTVhMGZlM2ExZGRmZWYzMGEzMDZhNCIsImVtYWlsIjoidGVzdHVzZXIxNEBnbWFpbC5jb20iLCJpYXQiOjE3NDMxMDIzNzcsImV4cCI6MTc0MzEwNTk3N30.KqDd-FKAW35Zu8wxzCTVZqK9AE38A1j3w4LCqS2TaY4

### Recuperar Password
POST http://localhost:3000/api/user/forgotpassword
Content-Type: application/json

{
    "email": "lihin57345@dizigg.com"
}

### Invitar Compañero
POST http://localhost:3000/api/user/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxMjMzNWE4M2JhYzIwNDE4MWJkMiIsImVtYWlsIjoidGVzdHVzZXIxMkBnbWFpbC5jb20iLCJpYXQiOjE3NDMxMDM4MzUsImV4cCI6MTc0MzEwNzQzNX0.CbeHbrNuw0j6yDR71dd-kN6NSLGnaXJ-gh-hTdpfGDg
Content-Type: application/json

{
    "email": "defibal183@dizigg.com"
}
